name: "Deploy Roger NO-OP"
on:
  repository_dispatch:
    types:
      - deploy-no-op

defaults:
  run:
    shell: bash

permissions:
  contents: read

env:
  LC_ALL: C.UTF-8

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: DO NOTHING
        run: echo 'Hello World!'